# Disable line-length check; it's too easy for the cure to be worse than the disease
Metrics/LineLength:
  Enabled: False

# Disable problematic module documentation check (see https://github.com/bbatsov/rubocop/issues/947)
Style/Documentation:
  Enabled: false

# Allow one line around class body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow one line around module body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow one line around block body (Layout/EmptyLines will still disallow two or more)
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Disable some style checks for sample code
Style/ClassAndModuleChildren:
  Exclude:
    - 'example.rb'

Style/MixinUsage:
  Exclude:
    - 'example.rb'
